#!/bin/bash -x

THIS_DIR=$(dirname "$0")
THIS_NAME=$(basename "$0")
SDK_PATH=external/carwos_sdk
SDK_BIN=${SDK_PATH}/usr/bin

LD_LIBRARY_PATH=${SDK_PATH}/usr/lib64:${SDK_PATH}/lib64

exec "${THIS_DIR}"/ld-2.26.so \
    "${SDK_BIN}"/"${THIS_NAME/carwos-/}" "${@}"
